# Generated by Django 5.0.3 on 2024-03-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_slug_profile_private'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='CustomUserProfile',
        ),
    ]
