# Generated by Django 5.0.3 on 2024-03-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_customuserprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserProfile',
            new_name='Profile',
        ),
    ]
